[project]
name = "Aesthetic-ImageGen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "google-genai>=1.41.0",
    "streamlit>=1.50.0",
]
